# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Belokan/ClionProjects/untitled7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Belokan/ClionProjects/untitled7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Belokan/ClionProjects/untitled7/CMakeFiles /Users/Belokan/ClionProjects/untitled7//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Belokan/ClionProjects/untitled7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled7

# Build rule for target.
untitled7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 untitled7
.PHONY : untitled7

# fast build rule for target.
untitled7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/build
.PHONY : untitled7/fast

AI/BaseAI.o: AI/BaseAI.cpp.o
.PHONY : AI/BaseAI.o

# target to build an object file
AI/BaseAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/BaseAI.cpp.o
.PHONY : AI/BaseAI.cpp.o

AI/BaseAI.i: AI/BaseAI.cpp.i
.PHONY : AI/BaseAI.i

# target to preprocess a source file
AI/BaseAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/BaseAI.cpp.i
.PHONY : AI/BaseAI.cpp.i

AI/BaseAI.s: AI/BaseAI.cpp.s
.PHONY : AI/BaseAI.s

# target to generate assembly for a file
AI/BaseAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/BaseAI.cpp.s
.PHONY : AI/BaseAI.cpp.s

AI/FollowAI.o: AI/FollowAI.cpp.o
.PHONY : AI/FollowAI.o

# target to build an object file
AI/FollowAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/FollowAI.cpp.o
.PHONY : AI/FollowAI.cpp.o

AI/FollowAI.i: AI/FollowAI.cpp.i
.PHONY : AI/FollowAI.i

# target to preprocess a source file
AI/FollowAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/FollowAI.cpp.i
.PHONY : AI/FollowAI.cpp.i

AI/FollowAI.s: AI/FollowAI.cpp.s
.PHONY : AI/FollowAI.s

# target to generate assembly for a file
AI/FollowAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/AI/FollowAI.cpp.s
.PHONY : AI/FollowAI.cpp.s

Components/AnimationComponent.o: Components/AnimationComponent.cpp.o
.PHONY : Components/AnimationComponent.o

# target to build an object file
Components/AnimationComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/AnimationComponent.cpp.o
.PHONY : Components/AnimationComponent.cpp.o

Components/AnimationComponent.i: Components/AnimationComponent.cpp.i
.PHONY : Components/AnimationComponent.i

# target to preprocess a source file
Components/AnimationComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/AnimationComponent.cpp.i
.PHONY : Components/AnimationComponent.cpp.i

Components/AnimationComponent.s: Components/AnimationComponent.cpp.s
.PHONY : Components/AnimationComponent.s

# target to generate assembly for a file
Components/AnimationComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/AnimationComponent.cpp.s
.PHONY : Components/AnimationComponent.cpp.s

Components/FightComponent.o: Components/FightComponent.cpp.o
.PHONY : Components/FightComponent.o

# target to build an object file
Components/FightComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/FightComponent.cpp.o
.PHONY : Components/FightComponent.cpp.o

Components/FightComponent.i: Components/FightComponent.cpp.i
.PHONY : Components/FightComponent.i

# target to preprocess a source file
Components/FightComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/FightComponent.cpp.i
.PHONY : Components/FightComponent.cpp.i

Components/FightComponent.s: Components/FightComponent.cpp.s
.PHONY : Components/FightComponent.s

# target to generate assembly for a file
Components/FightComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/FightComponent.cpp.s
.PHONY : Components/FightComponent.cpp.s

Components/HitboxComponent.o: Components/HitboxComponent.cpp.o
.PHONY : Components/HitboxComponent.o

# target to build an object file
Components/HitboxComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/HitboxComponent.cpp.o
.PHONY : Components/HitboxComponent.cpp.o

Components/HitboxComponent.i: Components/HitboxComponent.cpp.i
.PHONY : Components/HitboxComponent.i

# target to preprocess a source file
Components/HitboxComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/HitboxComponent.cpp.i
.PHONY : Components/HitboxComponent.cpp.i

Components/HitboxComponent.s: Components/HitboxComponent.cpp.s
.PHONY : Components/HitboxComponent.s

# target to generate assembly for a file
Components/HitboxComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/HitboxComponent.cpp.s
.PHONY : Components/HitboxComponent.cpp.s

Components/MovementComponent.o: Components/MovementComponent.cpp.o
.PHONY : Components/MovementComponent.o

# target to build an object file
Components/MovementComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/MovementComponent.cpp.o
.PHONY : Components/MovementComponent.cpp.o

Components/MovementComponent.i: Components/MovementComponent.cpp.i
.PHONY : Components/MovementComponent.i

# target to preprocess a source file
Components/MovementComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/MovementComponent.cpp.i
.PHONY : Components/MovementComponent.cpp.i

Components/MovementComponent.s: Components/MovementComponent.cpp.s
.PHONY : Components/MovementComponent.s

# target to generate assembly for a file
Components/MovementComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Components/MovementComponent.cpp.s
.PHONY : Components/MovementComponent.cpp.s

EditorState.o: EditorState.cpp.o
.PHONY : EditorState.o

# target to build an object file
EditorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/EditorState.cpp.o
.PHONY : EditorState.cpp.o

EditorState.i: EditorState.cpp.i
.PHONY : EditorState.i

# target to preprocess a source file
EditorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/EditorState.cpp.i
.PHONY : EditorState.cpp.i

EditorState.s: EditorState.cpp.s
.PHONY : EditorState.s

# target to generate assembly for a file
EditorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/EditorState.cpp.s
.PHONY : EditorState.cpp.s

Entities/Enemy.o: Entities/Enemy.cpp.o
.PHONY : Entities/Enemy.o

# target to build an object file
Entities/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Enemy.cpp.o
.PHONY : Entities/Enemy.cpp.o

Entities/Enemy.i: Entities/Enemy.cpp.i
.PHONY : Entities/Enemy.i

# target to preprocess a source file
Entities/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Enemy.cpp.i
.PHONY : Entities/Enemy.cpp.i

Entities/Enemy.s: Entities/Enemy.cpp.s
.PHONY : Entities/Enemy.s

# target to generate assembly for a file
Entities/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Enemy.cpp.s
.PHONY : Entities/Enemy.cpp.s

Entities/Entity.o: Entities/Entity.cpp.o
.PHONY : Entities/Entity.o

# target to build an object file
Entities/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Entity.cpp.o
.PHONY : Entities/Entity.cpp.o

Entities/Entity.i: Entities/Entity.cpp.i
.PHONY : Entities/Entity.i

# target to preprocess a source file
Entities/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Entity.cpp.i
.PHONY : Entities/Entity.cpp.i

Entities/Entity.s: Entities/Entity.cpp.s
.PHONY : Entities/Entity.s

# target to generate assembly for a file
Entities/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Entity.cpp.s
.PHONY : Entities/Entity.cpp.s

Entities/Player.o: Entities/Player.cpp.o
.PHONY : Entities/Player.o

# target to build an object file
Entities/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Player.cpp.o
.PHONY : Entities/Player.cpp.o

Entities/Player.i: Entities/Player.cpp.i
.PHONY : Entities/Player.i

# target to preprocess a source file
Entities/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Player.cpp.i
.PHONY : Entities/Player.cpp.i

Entities/Player.s: Entities/Player.cpp.s
.PHONY : Entities/Player.s

# target to generate assembly for a file
Entities/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Player.cpp.s
.PHONY : Entities/Player.cpp.s

Entities/Zombie.o: Entities/Zombie.cpp.o
.PHONY : Entities/Zombie.o

# target to build an object file
Entities/Zombie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Zombie.cpp.o
.PHONY : Entities/Zombie.cpp.o

Entities/Zombie.i: Entities/Zombie.cpp.i
.PHONY : Entities/Zombie.i

# target to preprocess a source file
Entities/Zombie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Zombie.cpp.i
.PHONY : Entities/Zombie.cpp.i

Entities/Zombie.s: Entities/Zombie.cpp.s
.PHONY : Entities/Zombie.s

# target to generate assembly for a file
Entities/Zombie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/Zombie.cpp.s
.PHONY : Entities/Zombie.cpp.s

Entities/elements/Sword.o: Entities/elements/Sword.cpp.o
.PHONY : Entities/elements/Sword.o

# target to build an object file
Entities/elements/Sword.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Sword.cpp.o
.PHONY : Entities/elements/Sword.cpp.o

Entities/elements/Sword.i: Entities/elements/Sword.cpp.i
.PHONY : Entities/elements/Sword.i

# target to preprocess a source file
Entities/elements/Sword.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Sword.cpp.i
.PHONY : Entities/elements/Sword.cpp.i

Entities/elements/Sword.s: Entities/elements/Sword.cpp.s
.PHONY : Entities/elements/Sword.s

# target to generate assembly for a file
Entities/elements/Sword.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Sword.cpp.s
.PHONY : Entities/elements/Sword.cpp.s

Entities/elements/Weapon.o: Entities/elements/Weapon.cpp.o
.PHONY : Entities/elements/Weapon.o

# target to build an object file
Entities/elements/Weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Weapon.cpp.o
.PHONY : Entities/elements/Weapon.cpp.o

Entities/elements/Weapon.i: Entities/elements/Weapon.cpp.i
.PHONY : Entities/elements/Weapon.i

# target to preprocess a source file
Entities/elements/Weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Weapon.cpp.i
.PHONY : Entities/elements/Weapon.cpp.i

Entities/elements/Weapon.s: Entities/elements/Weapon.cpp.s
.PHONY : Entities/elements/Weapon.s

# target to generate assembly for a file
Entities/elements/Weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Entities/elements/Weapon.cpp.s
.PHONY : Entities/elements/Weapon.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameState.o: GameState.cpp.o
.PHONY : GameState.o

# target to build an object file
GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/GameState.cpp.o
.PHONY : GameState.cpp.o

GameState.i: GameState.cpp.i
.PHONY : GameState.i

# target to preprocess a source file
GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/GameState.cpp.i
.PHONY : GameState.cpp.i

GameState.s: GameState.cpp.s
.PHONY : GameState.s

# target to generate assembly for a file
GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/GameState.cpp.s
.PHONY : GameState.cpp.s

MainMenuState.o: MainMenuState.cpp.o
.PHONY : MainMenuState.o

# target to build an object file
MainMenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/MainMenuState.cpp.o
.PHONY : MainMenuState.cpp.o

MainMenuState.i: MainMenuState.cpp.i
.PHONY : MainMenuState.i

# target to preprocess a source file
MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/MainMenuState.cpp.i
.PHONY : MainMenuState.cpp.i

MainMenuState.s: MainMenuState.cpp.s
.PHONY : MainMenuState.s

# target to generate assembly for a file
MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/MainMenuState.cpp.s
.PHONY : MainMenuState.cpp.s

Progress/Level.o: Progress/Level.cpp.o
.PHONY : Progress/Level.o

# target to build an object file
Progress/Level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level.cpp.o
.PHONY : Progress/Level.cpp.o

Progress/Level.i: Progress/Level.cpp.i
.PHONY : Progress/Level.i

# target to preprocess a source file
Progress/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level.cpp.i
.PHONY : Progress/Level.cpp.i

Progress/Level.s: Progress/Level.cpp.s
.PHONY : Progress/Level.s

# target to generate assembly for a file
Progress/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level.cpp.s
.PHONY : Progress/Level.cpp.s

Progress/Level1.o: Progress/Level1.cpp.o
.PHONY : Progress/Level1.o

# target to build an object file
Progress/Level1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level1.cpp.o
.PHONY : Progress/Level1.cpp.o

Progress/Level1.i: Progress/Level1.cpp.i
.PHONY : Progress/Level1.i

# target to preprocess a source file
Progress/Level1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level1.cpp.i
.PHONY : Progress/Level1.cpp.i

Progress/Level1.s: Progress/Level1.cpp.s
.PHONY : Progress/Level1.s

# target to generate assembly for a file
Progress/Level1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/Progress/Level1.cpp.s
.PHONY : Progress/Level1.cpp.s

State.o: State.cpp.o
.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i
.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s
.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/State.cpp.s
.PHONY : State.cpp.s

lib/UI/Background.o: lib/UI/Background.cpp.o
.PHONY : lib/UI/Background.o

# target to build an object file
lib/UI/Background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Background.cpp.o
.PHONY : lib/UI/Background.cpp.o

lib/UI/Background.i: lib/UI/Background.cpp.i
.PHONY : lib/UI/Background.i

# target to preprocess a source file
lib/UI/Background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Background.cpp.i
.PHONY : lib/UI/Background.cpp.i

lib/UI/Background.s: lib/UI/Background.cpp.s
.PHONY : lib/UI/Background.s

# target to generate assembly for a file
lib/UI/Background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Background.cpp.s
.PHONY : lib/UI/Background.cpp.s

lib/UI/Button.o: lib/UI/Button.cpp.o
.PHONY : lib/UI/Button.o

# target to build an object file
lib/UI/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Button.cpp.o
.PHONY : lib/UI/Button.cpp.o

lib/UI/Button.i: lib/UI/Button.cpp.i
.PHONY : lib/UI/Button.i

# target to preprocess a source file
lib/UI/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Button.cpp.i
.PHONY : lib/UI/Button.cpp.i

lib/UI/Button.s: lib/UI/Button.cpp.s
.PHONY : lib/UI/Button.s

# target to generate assembly for a file
lib/UI/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Button.cpp.s
.PHONY : lib/UI/Button.cpp.s

lib/UI/Label.o: lib/UI/Label.cpp.o
.PHONY : lib/UI/Label.o

# target to build an object file
lib/UI/Label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Label.cpp.o
.PHONY : lib/UI/Label.cpp.o

lib/UI/Label.i: lib/UI/Label.cpp.i
.PHONY : lib/UI/Label.i

# target to preprocess a source file
lib/UI/Label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Label.cpp.i
.PHONY : lib/UI/Label.cpp.i

lib/UI/Label.s: lib/UI/Label.cpp.s
.PHONY : lib/UI/Label.s

# target to generate assembly for a file
lib/UI/Label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/lib/UI/Label.cpp.s
.PHONY : lib/UI/Label.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/main.cpp.s
.PHONY : main.cpp.s

map/Map.o: map/Map.cpp.o
.PHONY : map/Map.o

# target to build an object file
map/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Map.cpp.o
.PHONY : map/Map.cpp.o

map/Map.i: map/Map.cpp.i
.PHONY : map/Map.i

# target to preprocess a source file
map/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Map.cpp.i
.PHONY : map/Map.cpp.i

map/Map.s: map/Map.cpp.s
.PHONY : map/Map.s

# target to generate assembly for a file
map/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Map.cpp.s
.PHONY : map/Map.cpp.s

map/Tile.o: map/Tile.cpp.o
.PHONY : map/Tile.o

# target to build an object file
map/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Tile.cpp.o
.PHONY : map/Tile.cpp.o

map/Tile.i: map/Tile.cpp.i
.PHONY : map/Tile.i

# target to preprocess a source file
map/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Tile.cpp.i
.PHONY : map/Tile.cpp.i

map/Tile.s: map/Tile.cpp.s
.PHONY : map/Tile.s

# target to generate assembly for a file
map/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/untitled7.dir/build.make CMakeFiles/untitled7.dir/map/Tile.cpp.s
.PHONY : map/Tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... untitled7"
	@echo "... AI/BaseAI.o"
	@echo "... AI/BaseAI.i"
	@echo "... AI/BaseAI.s"
	@echo "... AI/FollowAI.o"
	@echo "... AI/FollowAI.i"
	@echo "... AI/FollowAI.s"
	@echo "... Components/AnimationComponent.o"
	@echo "... Components/AnimationComponent.i"
	@echo "... Components/AnimationComponent.s"
	@echo "... Components/FightComponent.o"
	@echo "... Components/FightComponent.i"
	@echo "... Components/FightComponent.s"
	@echo "... Components/HitboxComponent.o"
	@echo "... Components/HitboxComponent.i"
	@echo "... Components/HitboxComponent.s"
	@echo "... Components/MovementComponent.o"
	@echo "... Components/MovementComponent.i"
	@echo "... Components/MovementComponent.s"
	@echo "... EditorState.o"
	@echo "... EditorState.i"
	@echo "... EditorState.s"
	@echo "... Entities/Enemy.o"
	@echo "... Entities/Enemy.i"
	@echo "... Entities/Enemy.s"
	@echo "... Entities/Entity.o"
	@echo "... Entities/Entity.i"
	@echo "... Entities/Entity.s"
	@echo "... Entities/Player.o"
	@echo "... Entities/Player.i"
	@echo "... Entities/Player.s"
	@echo "... Entities/Zombie.o"
	@echo "... Entities/Zombie.i"
	@echo "... Entities/Zombie.s"
	@echo "... Entities/elements/Sword.o"
	@echo "... Entities/elements/Sword.i"
	@echo "... Entities/elements/Sword.s"
	@echo "... Entities/elements/Weapon.o"
	@echo "... Entities/elements/Weapon.i"
	@echo "... Entities/elements/Weapon.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameState.o"
	@echo "... GameState.i"
	@echo "... GameState.s"
	@echo "... MainMenuState.o"
	@echo "... MainMenuState.i"
	@echo "... MainMenuState.s"
	@echo "... Progress/Level.o"
	@echo "... Progress/Level.i"
	@echo "... Progress/Level.s"
	@echo "... Progress/Level1.o"
	@echo "... Progress/Level1.i"
	@echo "... Progress/Level1.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... lib/UI/Background.o"
	@echo "... lib/UI/Background.i"
	@echo "... lib/UI/Background.s"
	@echo "... lib/UI/Button.o"
	@echo "... lib/UI/Button.i"
	@echo "... lib/UI/Button.s"
	@echo "... lib/UI/Label.o"
	@echo "... lib/UI/Label.i"
	@echo "... lib/UI/Label.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map/Map.o"
	@echo "... map/Map.i"
	@echo "... map/Map.s"
	@echo "... map/Tile.o"
	@echo "... map/Tile.i"
	@echo "... map/Tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

